### PR TITLE
Minimal pandas version (Fix issue 52)

### PR DESCRIPTION
**Pull request by eyaltrabelsi**
bump Minimal pandas version (Fix issue 52) #53

### CODE REVIEW

**Comment by HHammond** [comment]
Thanks for doing this, once CI is finished I'll ship it and update the package on pip

**Comment by eyaltrabelsi** [comment]
@HHammond Seems travis fail due to lack of version 3.3

**Comment by HHammond** [comment]
I'll modify the travis file.

**Comment by HHammond** [comment]
Update to Travis: https://github.com/HHammond/PrettyPandas/pull/54

**Pull request merged**
